  const express = require('express')
const router = express.Router()
const { login, protect } = require("../../controllers/seller/sellersControllers")
router.post("/login", login)
router.use("/account",  require("./routes/sellerRouter"))
router.use("/products", protect, require("./routes/productsRouter"))
router.use("/orders", protect, require("./routes/ordersRouter"))
router.use("/comments",protect,require("./routes/commentsRouter"))
router.use("/mails",protect,require("./routes/mailRouter"))
module.exports = router